add terraform summary to job summary

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -12,7 +12,7 @@ on:
 
 jobs:
   terraform:
-    name: "Terraform"
+    name: "Plan / Apply Terraform"
     runs-on: ubuntu-latest
     environment: home-server
 
@@ -64,9 +64,9 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+            const output = `\n#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`\n
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`\n
+            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`\n
             <details><summary>Validation Output</summary>
 
             \`\`\`\n
@@ -124,10 +124,38 @@ jobs:
               }
             }
 
-      - name: Exit if previous step failed
+      - name: Exit if any previous step with 'continue-on-error' failed
         if: steps.plan.outcome == 'failure' || steps.fmt.outcome == 'failure'
         run: exit 1
 
       - name: Terraform Apply
+        id: apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
+        run: |
+          # disable errexit temporarily so the step doesn't fail immediately if the following command fails 
+          set +e
+          terraform apply -auto-approve -input=false -no-color > apply_results.txt 2>&1
+          APPLY_EXIT_CODE=$?
+          set -e
+
+          if [ $APPLY_EXIT_CODE -eq 0 ]; then
+            echo "#### Terraform Apply ✅ (Success)" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "#### Terraform Apply ❌ (Failed)" >> $GITHUB_STEP_SUMMARY
+          fi
+
+          echo "<details><summary>Show Detailed Logs</summary>" >> $GITHUB_STEP_SUMMARY
+          
+          # add a newline to preserve formatting in details block
+          echo "" >> $GITHUB_STEP_SUMMARY
+
+          # wrap results in terraform-formatted code block
+          echo '```terraform' >> $GITHUB_STEP_SUMMARY
+          cat apply_results.txt >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+          # close 
+          echo "</details>" >> $GITHUB_STEP_SUMMARY
+
+          # exit with captured exit code
+          exit $APPLY_EXIT_CODE
